### ISSUE TITLE
pc-etherbcm contains etherbcm and etheryuk

### ISSUE THREAD

**Issue by lufia** [0intro/plan9-contrib#10]
I noticed pc-etherbcm.diff contains **/sys/src/9/pc/etheryuk.c** in 9legacy patches. Also there is pc-etheryuk.diff.

Is this correct?

http://www.9legacy.org/9legacy/patch/pc-etherbcm.diff
http://www.9legacy.org/9legacy/patch/pc-etheryuk.diff

**Comment by 0intro** [comment]
It seems to be a mistake. I've removed `etheryuk.c` from the `pc-etherbcm` patch.

Thanks for reporting!
