### ISSUE TITLE
regexp vs cmd/*

### ISSUE THREAD

**Issue by ghost** [0intro/plan9-contrib#8]
https://github.com/0intro/plan9-contrib/blob/master/sys/src/cmd/awk/re.c#L201
https://github.com/0intro/plan9-contrib/blob/master/sys/include/regexp.h#L12

Have you tested this code?

**Comment by ghost** [comment]
regexp.h needs 's' and 'e':

https://github.com/0intro/libregexp/blob/master/regexp9.h#L26
https://github.com/0intro/libregexp/blob/master/regexp9.h#L31

**Comment by lufia** [comment]
These are correct.

The compiler to compile awk is [pcc(1)](https://9p.io/magic/man2html/1/pcc) so **regexp.h** is located here:
https://github.com/0intro/plan9-contrib/blob/master/sys/include/ape/regexp.h#L22-L33

**Comment by lufia** [comment]
Plan 9's C compiler can embed some types in `struct` or `union` as anonymous fields, like Go.
https://9p.io/sys/doc/comp.html

**Comment by 0intro** [comment]
@lufia is right. The code is correct. The [plan9-contrib](https://github.com/0intro/plan9-contrib) code is Plan 9 code meant to be build with the Plan 9 C compiler, which handles anonymous struct and union. The [libregexp](https://github.com/0intro/libregexp) code is a Unix port of the previous code, meant to be built with GCC or Clang, which don't handle these extensions. A `-fplan9-extensions` parameter has been added to GCC a few years ago but there is no equivalent on Clang.

**Comment by ghost** [comment]
Thanks for explaining. This 's' and 'e' doesn't add anything, but it does result in code fragmentation and API incompatibility. It also doesn't make sense in the context of speed - access to memory will be slower.
